import type {
  Student,
  Teacher,
  Class,
  Subject,
  Payment,
  Commission,
} from '@/types'

export const dummyStudents: Student[] = [
  {
    id: 'STU001',
    name: 'Rahim Ahmed',
    email: 'rahim.ahmed@example.com',
    phone: '01900000001',
    class: 'SSC-10',
    enrollmentDate: '2024-01-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahim',
  },
  {
    id: 'STU002',
    name: 'Fatima Aktar',
    email: 'fatima.aktar@example.com',
    phone: '01900000002',
    class: 'SSC-10',
    enrollmentDate: '2024-01-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
  },
  {
    id: 'STU003',
    name: 'Karim Khan',
    email: 'karim.khan@example.com',
    phone: '01900000003',
    class: 'HSC-11',
    enrollmentDate: '2023-06-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karim',
  },
]

export const dummyTeachers: Teacher[] = [
  {
    id: 'TCH001',
    name: 'Dr. Rashedul Karim',
    email: 'rashedule.karim@example.com',
    phone: '01800000001',
    specialization: 'Mathematics',
    classes: ['SSC-10', 'HSC-11'],
    joinDate: '2020-03-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashedule',
  },
  {
    id: 'TCH002',
    name: 'Mrs. Sumaya Begum',
    email: 'sumaya.begum@example.com',
    phone: '01800000002',
    specialization: 'Bangla',
    classes: ['SSC-10'],
    joinDate: '2019-07-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sumaya',
  },
  {
    id: 'TCH003',
    name: 'Mr. Abdur Rahman',
    email: 'abdur.rahman@example.com',
    phone: '01800000003',
    specialization: 'English',
    classes: ['HSC-11', 'HSC-12'],
    joinDate: '2021-01-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdur',
  },
]

export const dummyClasses: Class[] = [
  {
    id: 'CLS001',
    name: 'SSC-10 (Science)',
    code: 'SSC-10-SCI',
    classTeacher: 'Dr. Rashedul Karim',
    totalStudents: 45,
    totalCapacity: 50,
    status: 'active',
    semester: '2024-2025',
    grade: '10',
  },
  {
    id: 'CLS002',
    name: 'SSC-10 (Humanities)',
    code: 'SSC-10-HUM',
    classTeacher: 'Mrs. Sumaya Begum',
    totalStudents: 38,
    totalCapacity: 45,
    status: 'active',
    semester: '2024-2025',
    grade: '10',
  },
  {
    id: 'CLS003',
    name: 'HSC-11',
    code: 'HSC-11-SCI',
    classTeacher: 'Mr. Abdur Rahman',
    totalStudents: 42,
    totalCapacity: 50,
    status: 'active',
    semester: '2024-2025',
    grade: '11',
  },
  {
    id: 'CLS004',
    name: 'HSC-12',
    code: 'HSC-12-SCI',
    classTeacher: 'Dr. Rashedul Karim',
    totalStudents: 40,
    totalCapacity: 50,
    status: 'active',
    semester: '2024-2025',
    grade: '12',
  },
  {
    id: 'CLS005',
    name: 'JSC',
    code: 'JSC-09-SCI',
    classTeacher: 'Mrs. Sumaya Begum',
    totalStudents: 56,
    totalCapacity: 60,
    status: 'active',
    semester: '2024-2025',
    grade: '9',
  },
  {
    id: 'CLS006',
    name: 'Primary 6',
    code: 'PRI-06-ALL',
    classTeacher: 'Mr. Abdur Rahman',
    totalStudents: 48,
    totalCapacity: 55,
    status: 'active',
    semester: '2024-2025',
    grade: '6',
  },
]

export const dummySubjects: Subject[] = [
  {
    id: 'SUB001',
    name: 'Mathematics',
    code: 'MATH-101',
    creditHours: 4,
    classes: ['SSC-10', 'HSC-11'],
    status: 'active',
  },
  {
    id: 'SUB002',
    name: 'Bangla',
    code: 'BNG-101',
    creditHours: 3,
    classes: ['SSC-10', 'HSC-11'],
    status: 'active',
  },
  {
    id: 'SUB003',
    name: 'English',
    code: 'ENG-101',
    creditHours: 3,
    classes: ['SSC-10', 'HSC-11'],
    status: 'active',
  },
  {
    id: 'SUB004',
    name: 'Science',
    code: 'SCI-101',
    creditHours: 4,
    classes: ['SSC-10', 'HSC-11'],
    status: 'active',
  },
  {
    id: 'SUB005',
    name: 'Social Science',
    code: 'SOC-101',
    creditHours: 3,
    classes: ['SSC-10'],
    status: 'active',
  },
]

export const dummyPayments: Payment[] = [
  {
    id: 'PAY001',
    studentId: 'STU001',
    studentName: 'Rahim Ahmed',
    amount: 12000,
    date: '2024-12-01',
    status: 'completed',
    type: 'tuition',
  },
  {
    id: 'PAY002',
    studentId: 'STU002',
    studentName: 'Fatima Aktar',
    amount: 12000,
    date: '2024-12-02',
    status: 'completed',
    type: 'tuition',
  },
  {
    id: 'PAY003',
    studentId: 'STU003',
    studentName: 'Karim Khan',
    amount: 10000,
    date: '2024-12-03',
    status: 'pending',
    type: 'tuition',
  },
  {
    id: 'PAY004',
    studentId: 'STU001',
    studentName: 'Rahim Ahmed',
    amount: 5000,
    date: '2024-12-05',
    status: 'completed',
    type: 'activity',
  },
  {
    id: 'PAY005',
    studentId: 'STU002',
    studentName: 'Fatima Aktar',
    amount: 1500,
    date: '2024-12-10',
    status: 'completed',
    type: 'other',
  },
  {
    id: 'PAY006',
    studentId: 'STU003',
    studentName: 'Karim Khan',
    amount: 12500,
    date: '2024-12-15',
    status: 'completed',
    type: 'tuition',
  },
]

export const dummyCommissions: Commission[] = [
  {
    id: 'COM001',
    name: 'Abbasi Ahmed',
    amount: 12000,
    date: '2024-12-01',
    status: 'active',
    commissionRate: 5,
  },
  {
    id: 'COM002',
    name: 'Najma Begum',
    amount: 10000,
    date: '2024-12-05',
    status: 'active',
    commissionRate: 4.5,
  },
  {
    id: 'COM003',
    name: 'Karim Mia',
    amount: 5000,
    date: '2024-11-28',
    status: 'active',
    commissionRate: 3,
  },
  {
    id: 'COM004',
    name: 'Fatema Khan',
    amount: 8500,
    date: '2024-12-10',
    status: 'pending',
    commissionRate: 4,
  },
]

export const paymentChartData = [
  { date: 'Dec 01', value: 45000 },
  { date: 'Dec 08', value: 52000 },
  { date: 'Dec 15', value: 48000 },
  { date: 'Dec 22', value: 61000 },
  { date: 'Dec 29', value: 55000 },
  { date: 'Jan 05', value: 67000 },
]

export const subjectDistributionData = [
  { name: 'Mathematics', value: 25 },
  { name: 'Bangla', value: 20 },
  { name: 'English', value: 20 },
  { name: 'Science', value: 18 },
  { name: 'Social Science', value: 17 },
]

// Dashboard statistics helper
export const getDashboardStats = () => {
  return {
    totalStudents: 1245,
    totalClasses: 56,
    totalTeachers: 32,
    totalSubjects: 24,
    totalPayments: 1245000,
    totalCommission: 124500,
    studentTrend: 12.5,
    classTrend: 8.3,
    teacherTrend: 5.2,
    subjectTrend: 10.0,
    paymentTrend: 9.6,
    commissionTrend: 15.8,
  }
}