import type {
  Student,
  Teacher,
  Class,
  Subject,
  Payment,
  Commission,
} from '@/types'

export const dummyStudents: Student[] = [
  {
    id: 'STU001',
    name: 'রহিম আহমেদ',
    email: 'rahim.ahmed@example.com',
    phone: '01900000001',
    class: 'এস এস সি-১০',
    enrollmentDate: '2024-01-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahim',
  },
  {
    id: 'STU002',
    name: 'ফাতিমা আক্তার',
    email: 'fatima.aktar@example.com',
    phone: '01900000002',
    class: 'এস এস সি-১০',
    enrollmentDate: '2024-01-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
  },
  {
    id: 'STU003',
    name: 'করিম খান',
    email: 'karim.khan@example.com',
    phone: '01900000003',
    class: 'এইচ এস সি-১১',
    enrollmentDate: '2023-06-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karim',
  },
]

export const dummyTeachers: Teacher[] = [
  {
    id: 'TCH001',
    name: 'ড. রাশেদুল করিম',
    email: 'rashedule.karim@example.com',
    phone: '01800000001',
    specialization: 'গণিত',
    classes: ['এস এস সি-১০', 'এইচ এস সি-১১'],
    joinDate: '2020-03-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashedule',
  },
  {
    id: 'TCH002',
    name: 'মিসেস সুমায়া বেগম',
    email: 'sumaya.begum@example.com',
    phone: '01800000002',
    specialization: 'বাংলা',
    classes: ['এস এস সি-১০'],
    joinDate: '2019-07-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sumaya',
  },
  {
    id: 'TCH003',
    name: 'মি. আবদুর রহমান',
    email: 'abdur.rahman@example.com',
    phone: '01800000003',
    specialization: 'ইংরেজি',
    classes: ['এইচ এস সি-১১', 'এইচ এস সি-১২'],
    joinDate: '2021-01-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdur',
  },
]

export const dummyClasses: Class[] = [
  {
    id: 'CLS001',
    name: 'এস এস সি-১০ (বিজ্ঞান)',
    code: 'SSC-10-SCI',
    classTeacher: 'ড. রাশেদুল করিম',
    totalStudents: 45,
    totalCapacity: 50,
    status: 'active',
    semester: '২০২৪-২০২৫',
    grade: '১০',
  },
  {
    id: 'CLS002',
    name: 'এস এস সি-১০ (মানবিক)',
    code: 'SSC-10-HUM',
    classTeacher: 'মিসেস সুমায়া বেগম',
    totalStudents: 38,
    totalCapacity: 45,
    status: 'active',
    semester: '২০२४-२०२५',
    grade: '१०',
  },
  {
    id: 'CLS003',
    name: 'এইচ এস সি-১১',
    code: 'HSC-11-SCI',
    classTeacher: 'মি. আবদুর রহমান',
    totalStudents: 42,
    totalCapacity: 50,
    status: 'active',
    semester: '२०२४-२०२५',
    grade: '११',
  },
  {
    id: 'CLS004',
    name: 'এইচ এস সি-१२',
    code: 'HSC-12-SCI',
    classTeacher: 'ড. রাশেদুল করিম',
    totalStudents: 40,
    totalCapacity: 50,
    status: 'active',
    semester: '२०२४-२०२५',
    grade: '१२',
  },
  {
    id: 'CLS005',
    name: 'জেএস सी',
    code: 'JSC-09-SCI',
    classTeacher: 'মিসেস সুমায়া বেগম',
    totalStudents: 56,
    totalCapacity: 60,
    status: 'active',
    semester: '२०२४-२०२५',
    grade: '९',
  },
  {
    id: 'CLS006',
    name: 'প্রাথমিক ৬',
    code: 'PRI-06-ALL',
    classTeacher: 'মি. আবদুর রহমান',
    totalStudents: 48,
    totalCapacity: 55,
    status: 'active',
    semester: '२०२४-०२०२५',
    grade: '६',
  },
]

export const dummySubjects: Subject[] = [
  {
    id: 'SUB001',
    name: 'গণিত',
    code: 'MATH-101',
    creditHours: 4,
    classes: ['এস এস সি-१०', 'এইচ এস সি-११'],
    status: 'active',
  },
  {
    id: 'SUB002',
    name: 'বাংলা',
    code: 'BNG-101',
    creditHours: 3,
    classes: ['এস এস সি-१०', 'এইচ এস সি-११'],
    status: 'active',
  },
  {
    id: 'SUB003',
    name: 'ইংরেজি',
    code: 'ENG-101',
    creditHours: 3,
    classes: ['এস এस सी-१०', 'एইच एस सी-११'],
    status: 'active',
  },
  {
    id: 'SUB004',
    name: 'বিজ্ঞান',
    code: 'SCI-101',
    creditHours: 4,
    classes: ['এস এস সी-१०', 'এইच এस সी-११'],
    status: 'active',
  },
  {
    id: 'SUB005',
    name: 'সামাজিক বিজ্ঞান',
    code: 'SOC-101',
    creditHours: 3,
    classes: ['এস এস সी-१०'],
    status: 'active',
  },
]

export const dummyPayments: Payment[] = [
  {
    id: 'PAY001',
    studentId: 'STU001',
    studentName: 'রহিম আহমেদ',
    amount: 12000,
    date: '2024-12-01',
    status: 'completed',
    type: 'tuition',
  },
  {
    id: 'PAY002',
    studentId: 'STU002',
    studentName: 'ফাতিমা আক্তার',
    amount: 12000,
    date: '2024-12-02',
    status: 'completed',
    type: 'tuition',
  },
  {
    id: 'PAY003',
    studentId: 'STU003',
    studentName: 'করিম খান',
    amount: 10000,
    date: '2024-12-03',
    status: 'pending',
    type: 'tuition',
  },
  {
    id: 'PAY004',
    studentId: 'STU001',
    studentName: 'রহিম আহমেদ',
    amount: 5000,
    date: '2024-12-05',
    status: 'completed',
    type: 'activity',
  },
  {
    id: 'PAY005',
    studentId: 'STU002',
    studentName: 'ফাতিমা আক্তার',
    amount: 1500,
    date: '2024-12-10',
    status: 'completed',
    type: 'other',
  },
  {
    id: 'PAY006',
    studentId: 'STU003',
    studentName: 'করিম খান',
    amount: 12500,
    date: '2024-12-15',
    status: 'completed',
    type: 'tuition',
  },
]

export const dummyCommissions: Commission[] = [
  {
    id: 'COM001',
    name: 'আব্বাসী আহমেদ',
    amount: 12000,
    date: '2024-12-01',
    status: 'active',
    commissionRate: 5,
  },
  {
    id: 'COM002',
    name: 'নাজমা বেগম',
    amount: 10000,
    date: '2024-12-05',
    status: 'active',
    commissionRate: 4.5,
  },
  {
    id: 'COM003',
    name: 'করিম মিয়া',
    amount: 5000,
    date: '2024-11-28',
    status: 'active',
    commissionRate: 3,
  },
  {
    id: 'COM004',
    name: 'ফাতেমা খান',
    amount: 8500,
    date: '2024-12-10',
    status: 'pending',
    commissionRate: 4,
  },
]

export const paymentChartData = [
  { date: 'ডিসেম্বর ০১', value: 45000 },
  { date: 'ডিসেম্বর ০৮', value: 52000 },
  { date: 'ডিসেম্বর १५', value: 48000 },
  { date: 'ডিসেম্বর २२', value: 61000 },
  { date: 'ডিসেম্বর २९', value: 55000 },
  { date: 'জানুয়ারি ०५', value: 67000 },
]

export const subjectDistributionData = [
  { name: 'গণিত', value: 25 },
  { name: 'বাংলা', value: 20 },
  { name: 'ইংরেজি', value: 20 },
  { name: 'বিজ্ঞান', value: 18 },
  { name: 'সামাজিক বিজ্ঞান', value: 17 },
]

// Dashboard statistics helper
export const getDashboardStats = () => {
  return {
    totalStudents: 1245,
    totalClasses: 56,
    totalTeachers: 32,
    totalSubjects: 24,
    totalPayments: 1245000,
    totalCommission: 124500,
    studentTrend: 12.5,
    classTrend: 8.3,
    teacherTrend: 5.2,
    subjectTrend: 10.0,
    paymentTrend: 9.6,
    commissionTrend: 15.8,
  }
}
